# Generated by Django 3.1.6 on 2021-02-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0003_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='categories',
            field=models.ManyToManyField(to='app_base.Category'),
        ),
    ]
